---
name: "⭕ Trunk"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "⤵️  Check out code from GitHub"
        uses: actions/checkout@v4
      - name: "⭕ Trunk Check"
        uses: trunk-io/trunk-action@cf57c926b78958033bf9be80b9b92a286f15b246
